name: NinjaEdit
main: com.ninja.NinjaEdit.NinjaEdit
version: 1.0.4
commands:
   /pos1:
      description: Set's a NinjaEdit pos
      usage: //pos1
   /pos2:
      description: Set's a NinjaEdit pos
      usage: //pos2
   /set:
      description: Set's marked position to a block
      usage: //set <id>
   /replace:
      description: Replaces blocks in selection
      usage: //replace <id> <id>
   /undo:
      description: Undo stuff
      usage: //undo
   /redo:
      description: Redo stuff
      usage: //redo
   /up:
      description: Go up.
      usage: //up <value> 
   /copy:
      description: Copy your selection to your clipboard.
      usage: //copy
   /paste:
      description: Paste your clipboard.
      usage: //paste
   /cut:
      description: Cut the selection to your clipboard.
      usage: //cut
   /stack:
      description: Stack your selection in a direction.
      usage: //stack <amount> <dir>
   /wand:
      description: Gives you a magical wand.
      usage: //wand
   /move:
      description: Move your clipboard in a direction.
      usage: //move <amount> <dir>
   /getid:
      description: Get id of blocks.
      usage: //getid
   /expand:
      description: Expand the region.
      usage: //expand <amount> <dir | look>
   /contract:
      description: Contract the region.
      usage: //contract <amount> <dir | look>